# ============================================================================
# PLACEHOLDER — THIS IS NOT A REAL HARDWARE CONFIG.
#
# Replace this entire file with the output of, run ON the thinkpad itself:
#
#     nixos-generate-config --show-hardware-config
#
# It has to be generated there because it encodes that machine's filesystems,
# LUKS UUIDs, initrd kernel modules and CPU microcode — none of which can be
# guessed from here.
#
# Until you do, `nixos-rebuild build --flake .#thinkpad` and `nix flake check`
# fail with:
#
#     The 'fileSystems' option does not specify your root file system.
#
# That failure is deliberate. A placeholder that evaluated successfully could
# silently build an unbootable system, so this one refuses to build at all.
# If the failing `nix flake check` is in your way, comment out the `thinkpad`
# line in flake.nix until the laptop is installed.
# ============================================================================
i# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f235d82-5e9f-43f7-8242-881287eb2166";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BC7C-8FBE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

